mysite/myapp/urls.py
from django.urls import path
from . import views

from django.views.decorators.cache import cache_page

app_name='myapp'

urlpatterns = [
  path('', views.index, name='index'),
  path('<int:id>/', views.detail, name='detail'),
  path('add/', views.create_item, name='create_item'),
  path('update/<int:pk>/', views.ItemUpdateView.as_view(), name='update'),
  path('delete/<int:pk>/', views.ItemDeleteView.as_view(), name='delete'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myapp/', include('myapp.urls')),
    path('users/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
   path('register/', views.register, name='register'),
   path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
   path('logout/', views.logout_view, name='logout'),
   path('profile/', views.profile, name='profile'),
]

mysite/myapp/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from .managers import ItemManager

from django.utils import timezone

class Item(models.Model):
  
  class Meta:
    indexes = [
      models.Index(fields=['user_name', 'item_price']),
    ]

  def __str__(self):
    return self.item_name + ": " + str(self.item_price)
  
  def get_absolute_url(self):
    return reverse('myapp:index')
  
  def delete(self, using=None, keep_parents=False):
    self.is_deleted = True
    self.deleted_at = timezone.now()
    self.save()

  user_name = models.ForeignKey(User, on_delete=models.CASCADE)
  item_name = models.CharField(max_length=200, db_index=True)
  item_desc = models.CharField()
  item_price = models.DecimalField(max_digits=4, decimal_places=2, db_index=True)
  item_image = models.URLField(max_length=500, default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRHCva-afP1vczYjMkGUFt4QQ51zwKM2q3GcQ&s')
  is_available = models.BooleanField(default=True)
  created_at = models.DateTimeField(auto_now_add=True)

  is_deleted = models.BooleanField(default=False) # soft delete  flag

  deleted_at = models.DateTimeField(null=True, blank=True)

  objects = ItemManager()
  all_objects = models.Manager()

class Category(models.Model):
  name = models.CharField(max_length=100)
  added_on = models.DateField(auto_now=True)

  def __str__(self):
    return self.name

mysite/users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='profilepic.jpg', upload_to='profile_pictures')
    location = models.CharField(max_length=100)

    def __str__(self):
        return self.user.username 

mysite/myapp/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
  class Meta:
    model = Item
    fields = ['item_name', 'item_desc', 'item_price', 'item_image']
    widgets = {
      "item_name": forms.TextInput(attrs={
        "placeholder": "e.g. Margarita Pizza",
        "required": True,
        }),
      "item_desc": forms.TextInput(attrs={
        "placeholder": "e.g. Fresh and cheesy",
        "required": True,
        }),
      "item_price": forms.NumberInput(attrs={
        "placeholder": "100",
        "required": True,
        }),
      "item_image": forms.URLInput(attrs={
        "placeholder": "https://www.google.com",
        "required": False,
        }),
    }
  
  def clean_item_price(self):
    price = self.cleaned_data["item_price"]
    if price < 0:
      raise forms.ValidationError("Price cannot be negative")
    return price

  def clean(self):
    cleaned = super().clean()
    name = cleaned.get("item_name")
    desc = cleaned.get("item_desc")

    if name and desc and name.lower() in desc.lower():
      self.add_error("item_desc", "Description should add new info beyond the name")
    return cleaned 

mysite/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User

class RegisterForm(UserCreationForm):
  email = forms.EmailField()

  class Meta:
    model = User
    fields = ['username', 'email', 'password1', 'password2']

mysite/myapp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.core.paginator import Paginator
from django.views.decorators.cache import cache_page
from django.views.decorators.vary import vary_on_headers
from django.shortcuts import get_object_or_404
from django.utils import timezone

from .models import Item
from .forms import ItemForm

import logging

logger = logging.getLogger(__name__)

# @cache_page(60 * 15)
# @vary_on_headers("User-Agent")
@login_required
def index(request):
  logger.info("Fetching all items from the database")
  logger.info(f"User [{timezone.now().isoformat()}] {request.user} requested item_list from {request.META.get('REMOTE_ADDR')}")
  item_list = Item.objects. all()
  logger.debug(f"Found {item_list.count()} items ")
  paginator = Paginator(item_list, 5)
  page_number = request.GET.get("page")
  page_obj = paginator.get_page(page_number)

  context = {
    'page_obj': page_obj,
  }
  return  render(request, "myapp/index.html", context)


class IndexClassView(ListView):
  model = Item
  template_name = "myapp/index.html"
  context_object_name = 'item_list'

def detail (request, id):
  logger.info(f"Fetching an item with id: {id}")
  try:
    item = get_object_or_404(Item, pk=id)
    logger.debug(f"Item found {item.item_name} ($ {item.item_price})")
  except Exception as e:
    logger.error(f"Error fetching the item %s: %s", id, e)
    raise 
  context = {
    'item': item
  } 
  return render(request, 'myapp/detail.html', context)

class FoodDetail(DetailView):
  model = Item
  template_name = 'myapp/detail.html'
  context_object_name = 'item'

def create_item(request):
  form = ItemForm(request.POST or None)
  if request.method == 'POST':
    if form.is_valid():
      form.save()
      return redirect('myapp:index')

  context={
    'form': form
  }
  return render(request, 'myapp/item-form.html', context)

class ItemCreateView(CreateView):
  model = Item
  fields = ['item_name', 'item_desc', 'item_price', 'item_image']

  def form_valid(self, form):
    form.instance.user_name = self.request.user
    return super().form_valid(form)


def update_item(request, id):
  item = Item.objects.get(id=id)
  form=ItemForm(request.POST or None, instance=item)

  if form.is_valid():
    form.save()
    return redirect('myapp:index')

  context = {
    'form': form
  }
  return render(request, 'myapp/item-form.html', context)

class ItemUpdateView(UpdateView):
  model = Item
  fields = ['item_name', 'item_desc', 'item_price', 'item_image']
  template_name_suffix = '_update_form'

def delete_item(request, id):
  item = Item.objects.get(id=id)
  if request.method == 'POST':
    item.delete()
    return redirect('myapp:index')
      
  return render(request, 'myapp/item-delete.html')

class ItemDeleteView(DeleteView):
  model = Item
  success_url = reverse_lazy('myapp:index')


# def get_objects(request):
#   for item in Item.objects.all():
#     print(item.item_name)

# def get_objects_optimized(request):
#   items = Item.objects.only('item_name')

#   for item in items:
#     print(item.item_name)

mysite/users/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import RegisterForm
from django.contrib.auth import logout

# Create your views here.

def register(request):
  form = RegisterForm(request.POST or None)
  if request.method == "POST":
    if form.is_valid():
      username = form.cleaned_data.get('username')
      messages.success(request, f'Welcome {username}, your account has been successfully created')
      form.save()
      return redirect('login')

  
  return  render(request, 'users/register.html', {'form': form})

def logout_view(request):
  logout(request)
  return render(request, 'users/logout.html')

@login_required
def profile(request):

  return render(request, 'users/profile.html')

mysite/myapp/templates/myapp/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
    <title>Document</title>
  </head>
  <body>
    <nav class="bg-blue-600 text-white">
      <div class="flex justify-between px-2 py-4">
        <a href="" class="font-bold text-2xl">FoodApp</a>
        <div class="space-x-6">
          <a href="{% url 'profile' %}">Welcome {{user.username}}!</a>
          {% if user.is_authenticated %}
          <a href="{% url 'logout' %}">Logout</a> {% else %}
          <a href="{% url 'login' %}">Login</a> {% endif %}
        </div>
      </div>
    </nav>

    {% if messages%} {% for message in messages %}
    <div class="bg-green-500 text-green-700">{{message}}</div>
    {% endfor %} {% endif %} {% block body %} {% endblock %}
  </body>
</html>

mysite/myapp/templates/myapp/detail.html
{% extends 'myapp/base.html' %} {% block body %}
<div class="m-10 flex">
  <div><img class="w-128 rounded-lg" src="{{item.item_image}} alt=""></div>
  <div class="mx-16 space-y-5">
    <div class="font-bold text-4xl">{{item.item_name}}</div>
    <div class="font-bold text-green-700 text-2xl">${{item.item_price}}</div>
    <div>{{item.item_desc}}</div>
    <div>
      {% if item.user_name == request.user %}
      <a
        class="bg-yellow-500 px-4 py-2 rounded-md font-bold text-white"
        href="{% url 'myapp:update' item.id %}"
        >Edit</a
      >
      <a
        class="bg-red-500 px-4 py-2 rounded-md font-bold text-white"
        href="{% url 'myapp:delete' item.id %}"
        >Delete</a
      >{% endif %}
    </div>
  </div>
</div>
{% endblock %}

mysite/myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %} {% load custom_filters %}
{% block body %}
  {% load cache %}
  <div>
    {% cache 900 page_obj %}
    {% for item in page_obj %}
      <div class="m-10 flex w-1/2 mx-auto">
        <div>
          <img class="w-64 rounded-lg" src="{{ item.item_image }}" alt="" />
        </div>
        <div class="mx-16">
          <div class="font-bold">{{ item.item_name|upper }}</div>
          <div>{{ item.item_desc|lower|truncatechars:30 }}</div>
          <div>{{ item.user_name }}</div>
          <div>{{ item.created_at|timesince }} ago</div>
          <div class="font-bold text-green-700">{{ item.item_price|currency }}</div>
          <div>Discounted price: {{ item.item_price|discount:10 }}</div>
        </div>
        <div>
          <a class="bg-red-500 text-white font-bold px-4 py-2 rounded-md" href="{% url 'myapp:detail' item.id %}">View Details</a>
        </div>
      </div>
    {% endfor %}
    {% endcache %}
  </div>
  <div class="flex items-centered justify-center space-x-4 py-4">
    {% if page_obj.has_previous %}
      <a href="?page={{ page_obj.previous_page_number }}" class="px-4 py-2 rounded-lg bg-gray-200 text-gray-700 hover:bg-gray-300">Previous</a>
    {% endif %}
    <span>Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</span>
    {% if page_obj.has_next %}
      <a href="?page={{ page_obj.next_page_number }}" class="px-4 py-2 rounded-lg bg-gray-200 text-gray-700 hover:bg-gray-300">Next</a>
    {% endif %}
  </div>
{% endblock %}

mysite/myapp/templates/myapp/item-delete.html
<form method="POST">
  {% csrf_token %}
  <h2>Are you sure you want to delete the item ?</h2>
  <button>Confirm</button>
</form>

mysite/myapp/templates/myapp/item-form.html
{% extends 'myapp/base.html' %} {% block body %}
  <div class="flex flex-col justify-center items-center min-h-screen p-10">
    <h1>Add item</h1>
    {{ form.errors }}
    <form method="POST" class="shadow-lg space-y-6 p-10 w-96">
      {% csrf_token %} {% if form.non_field_errors %}
        <div class="bg-red-500 text-white p-2">
          {% for error in form.non_field_errors %}
            <p>{{ error }}</p>
          {% endfor %}
        </div>
      {% endif %} {% for field in form %}
        <label for="">{{ field.label }}</label>
        <div class="border rounded p-2">{{ field }}</div>
      {% endfor %}
      <button class="bg-blue-500 text-white px-4 py-2 w-full" type="submit">Save</button>
    </form>
  </div>
{% endblock %}

mysite/myapp/templates/myapp/item_confirm_delete.html
<form method="POST">
  {%csrf_token%} Are you sure you want to delete this item ?
  <input type="submit" name="" id="" />
</form>

mysite/myapp/templates/myapp/item_form.html
{% extends 'myapp/base.html' %} {% block body %}
<div class="flex flex-col justify-center items-center min-h-screen p-10">
  <h1>Add item</h1>
  <form method="POST" class="shadow-lg space-y-6 p-10 w-96">
    {% csrf_token %} {% if form.non_field_errors %}
    <div class="bg-red-500 text-white p-2">
      {% for error in form.non_field_errors %}
      <p>{{error}}</p>
      {% endfor %}
    </div>
    {% endif %} {%for field in form%}
    <label for="">{{field.label}}</label>
    <div class="border rounded p-2">{{field}}</div>
    {% endfor %}
    <button class="bg-blue-500 text-white px-4 py-2 w-full" type="submit">
      Save
    </button>
  </form>
</div>
{% endblock %}

mysite/myapp/templates/myapp/item_update_form.html
<form method="POST">
  {% csrf_token %} {{form}} <input type="submit" name="" id="" />
</form>

mysite/users/templates/users/login.html
{% extends 'myapp/base.html' %} {% block body %}

<div class="flex flex-col justify-center items-center min-h-screen p-10">
  <h1>Login</h1>
  <form method="POST" class="shadow-lg p-10 space-y-10">
    {% csrf_token %} {% if form.non_field_errors %}
    <div class="bg-red-500 text-white p-2">
      {% for error in form.non_field_errors %}
      <p>{{error}}</p>
      {% endfor %}
    </div>
    {% endif %}
    <div>
      <label for="">Username</label>
      <div class="border rounded p-2">{{form.username}}</div>
    </div>
    <div>
      <label for="">Password</label>
      <div class="border rounded p-2">{{form.password}}</div>
    </div>
    <button class="bg-blue-500 px-2 py-2 w-full text-white" type="submit">
      Login
    </button>
  </form>
</div>
{% endblock %}

mysite/users/templates/users/logout.html
<h2>Yout have logged out</h2>

mysite/users/templates/users/profile.html
<h1>{{user.username}}</h1>
<img src="{{user.profile.image.url}}" alt="" />

mysite/users/templates/users/register.html
{% extends 'myapp/base.html' %} {% block body %}
<div class="flex flex-col justify-center items-center min-h-screen p-10">
  <h1>Signup</h1>
  <form method="POST" class="shadow-lg space-y-6 p-10 w-96">
    {% csrf_token %} {% if form.non_field_errors %}
    <div class="bg-red-500 text-white p-2">
      {% for error in form.non_field_errors %}
      <p>{{error}}</p>
      {% endfor %}
    </div>
    {% endif %} {% for field in form %}
    <div>
      <label for="">{{field.label}}</label>
      <div class="border rounded p-2">{{field}}</div>
    </div>
    {% endfor %}
    <button class="bg-blue-500 text-white px-4 py-2 w-full">Signup</button>
  </form>
</div>

{% endblock %}